app:
  jwt_secret_key: ${JWT_SECRET_KEY}
  access_token_expiry: 2h
  refresh_token_expiry: 168h

server:
  host: 0.0.0.0
  port: 8080

database:
  user: postgres
  password: ${DATABASE_PASSWORD}
  host: chipsi-postgres
  port: 5432
  dbname: chipsi
  sslMode: false

smtp:
  from: inftop@yandex.ru
  host: smtp.yandex.ru
  port: 465
  username: inftop@yandex.ru
  password: ${SMTP_PASSWORD}
